export const incidentList =[
    "Fire Alarm",
    "Property Damage",
    "Barrier Damage",
    "Barrier Mulfunction",
    "Equipment Accident",
    "Machinary Accident",
    "Electrical Faults",
    "Electrocution",
    "Vehicle Breakdown",
    "Vehicle Accident",
    "Slip and Fall",
    "Fatigue",
    "Unsafe Lifting",
    "Chemical Exposure",
    "Falling Objects",
    "Unauthorized Access",
    "Theft",
    "Signage Damage",
    "Water Lickage",
    "Oil Spillage",
    "Employee Complaints",
    "Disorderly Conduct",
    "Improper Records",
    "Others",
  ];